name: 'Cloudways API Git Pull'
description: 'Github Action to deploy your project to Cloudways.'
inputs:
  server-id:
    description: 'Cloudways Server ID'
    required: true
  app-id:
    description: 'Cloudways App ID'
    required: true
  branch-name:
    description: 'The Git branch you are pulling the changes'
    required: true
  deploy-path:
    description: 'The path you are deploying the changes (ignore public_html string)'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
